### ISSUE TITLE
Github repo in Pub is wrong

### ISSUE THREAD

**Issue by stevenroose** [richerlariviere/bootstrap_for_pub#17]
Either the repo should be moved or the pubspec should be updated:
https://github.com/sethladd/bootstrap_for_pub/blob/master/pubspec.yaml#L10

**Comment by richerlariviere** [comment]
Fixed: f020c3c29f06dad49ef801ee8b4c97aa272d3269

The repo now on Pub now link to github.com/richerlariviere/bootstrap_for_pub
