### ISSUE TITLE
Version 4 support

### ISSUE THREAD

**Issue by madisona** [richerlariviere/bootstrap_for_pub#18]
I know it is still 4.0.0-alpha.6, but it would nice to use this package with version 4.  

Production would currently work because of the transformer pointing to the CDN, but the local files are at version 3.3.7

**Comment by madisona** [comment]
I submitted pull request #19 to update the bootstrap files to 4.0.0-alpha.6

**Comment by richerlariviere** [comment]
Hi @madisona. I am sorry for the response time. Thanks for the PR. Will merge.
