### ISSUE TITLE
Transformer is not working in "pub build"

### ISSUE THREAD

**Issue by rafbermudez** [richerlariviere/bootstrap_for_pub#20]
I add this code in my index.html

```
<script src="packages/bootstrap/jquery/jquery.js"></script>
<script src="packages/bootstrap/js/bootstrap.js"></script>
```

The project works fine in my local machine with pub serve. It's using the path "build/packages/bootstrap/jquery/jquery.js"

After run "pub build" I get this error:

```
GET http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/jquery/jquery.min.js 403 (Forbidden)
bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:6
```

It seems that http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/jquery/jquery.min.js is not a valid path. Doesn't exist!

My pubspec.yaml contains:
```
- bootstrap:
    url: //maxcdn.bootstrapcdn.com/bootstrap/{{version}}
    version: 3.3.7
```

Any idea? Thanks!

**Comment by richerlariviere** [comment]
Hi @rafbermudez,

I looked over your issue and I can confirm that jQuery is no longer packaged with Bootstrap (using BootstrapCDN). The Transformer logic will have to be fixed. As a quick workaround, you could use the [current recommended jquery CDN](https://code.jquery.com/) and hardcode it into your html file. At this moment, you can use jquery 3.2.1 safely.
```
https://code.jquery.com/jquery-3.2.1.js
```
I'm very busy in the following 2 weeks. Feel free to submit a PR if you have time to patch this bug I will be more than happy to merge it :).

**Comment by richerlariviere** [comment]
I think we shoud add another Transformer, which will import jQuery library using specified CDN in pubspec.yaml

**Comment by rafbermudez** [comment]
Thanks for the workarround!

I'm not applying the Transformer now. My application is for internal use only. Using directly  "/bootstrap/jquery/jquery.js" is valid to me.

**Comment by richerlariviere** [comment]
Please see this [https://github.com/richerlariviere/bootstrap_for_pub/issues/22](discussion)
