### ISSUE TITLE
Add CI Badge to README, turn on Travis

### ISSUE THREAD

**Issue by jvarness** [richerlariviere/bootstrap_for_pub#27]
https://travis-ci.org/richerlariviere/bootstrap_for_pub

I don't have privileges to turn Travis on for this repo. It would be good to have the badge on the README as well.

**Comment by richerlariviere** [comment]
Done -> f42f0cea5b6dbda4396baaa46568d40918e39670

**Comment by richerlariviere** [comment]
I'm working right now to activate Travis for this repo. Thanks for your help it's amazing and really appreciated :)
