### ISSUE TITLE
Release latest master to pub?

### ISSUE THREAD

**Issue by alademann** [richerlariviere/bootstrap_for_pub#28]
Hi there,

First off, let me say... thanks for your work on this!!!

It appears that the master branch of this repository has a commit that moves from depending on `html5lib` to `html` (https://github.com/richerlariviere/bootstrap_for_pub/commit/83b274f294dc6792017be0986689332799c84688). 

Are there any plans to `pub publish` the latest master?

**Comment by richerlariviere** [comment]
I'll merge your PR and update pub tonight when I get home. Thanks for your work I'm really busy these times so your help is really appreciated :) :) :). I'll let you know once it's done.

**Comment by richerlariviere** [comment]
Done. Sorry for the big delay. I got unexpected events in my life that prevented me to contribute. Enjoy
